import ../ast/doc as astdoc
import ../ast/print as astprint
import ../diag/engine as diagengine
import ../diag/palette as diagpalette
import ../diag/render as diagrender
import ../diag/span as diagspan
import ../lex/lexer as lexlexer
import ../lex/token as lextoken
import ../parse/control as parsecontrol
import ../parse/expression as parseexpression
import ../parse/generics as parsegenerics
import ../parse/machine as parsemachine
import ../parse/native as parsenative
import ../parse/parser as parseparser
import ../sema/bindings as semabindings
import ../sema/link as semalink
import ../sema/module as semamodule
import ../sema/resolver as semaresolver
import ../sema/scope as semascope
import ../types/borrow as typesborrow
import ../types/checker as typeschecker
import ../types/coerce as typescoerce
import ../types/escape as typesescape
import ../types/exhaust as typesexhaust
import ../types/foundation as typesfoundation

echo "syntax suite: ok"
