#ifndef FOO_SERVICE_H
#define FOO_SERVICE_H
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
typedef struct {
  const uint8_t *data;
  size_t len;
} FooText;
typedef struct {
  int error;
  void *pointer;
  uint64_t number;
  FooText text;
} FooResult;
void foo_service_init(int count, char **arguments);
void foo_service_close(void);
FooResult foo_cpu_runtime(FooText feature);
FooResult foo_topology_count(void);
FooResult foo_topology_allowed(void);
FooResult foo_topology_current(void);
FooResult foo_topology_nodes(void);
FooResult foo_topology_node(uint64_t cpu);
FooResult foo_topology_place(uint64_t node);
FooResult foo_topology_pin(uint64_t cpu);
FooResult foo_topology_restore(void *placement);
FooResult foo_platform_page(void);
FooResult foo_platform_width(void);
FooResult foo_platform_alignment(void);
FooResult foo_platform_little(void);
FooResult foo_platform_supports(FooText feature);
FooResult foo_cpu_add(FooText left, FooText right, FooText output);
FooResult foo_cpu_vectorize(FooText left, FooText right, FooText output,
                            uint64_t count, uint64_t width, uint64_t operation,
                            uint64_t start, uint64_t flags, double first,
                            double second, uint64_t post_operation, double post,
                            uint64_t *index);
FooResult foo_gpu_available(void);
FooResult foo_gpu_open(void);
FooResult foo_gpu_name(void *device);
FooResult foo_gpu_capacity(void *device);
FooResult foo_gpu_supports(void *device, FooText feature);
FooResult foo_gpu_reserve(void *device, uint64_t size);
FooResult foo_gpu_mapped(void *buffer);
FooResult foo_gpu_mutable(void *buffer);
FooResult foo_gpu_upload(void *buffer, FooText source);
FooResult foo_gpu_download(void *buffer, FooText destination);
FooResult foo_gpu_send(void *buffer, FooText source);
FooResult foo_gpu_receive(void *buffer, FooText destination);
FooResult foo_gpu_push(void *buffer, FooText source);
FooResult foo_gpu_pull(void *buffer, FooText destination);
FooResult foo_gpu_prepared(void *device, FooText source, FooText entry,
                           FooText widths, uint64_t localLimit,
                           uint64_t requirements, uint64_t localBytes);
FooResult foo_gpu_bind(void *kernel, uint64_t index, void *buffer);
FooResult foo_gpu_launch(void *kernel, uint64_t count);
FooResult foo_gpu_dispatch(void *kernel, uint64_t count, uint64_t group);
FooResult foo_gpu_plane(void *kernel, uint64_t x, uint64_t y,
                        uint64_t localx, uint64_t localy);
FooResult foo_gpu_volume(void *kernel, uint64_t x, uint64_t y, uint64_t z,
                         uint64_t localx, uint64_t localy, uint64_t localz);
FooResult foo_gpu_finish(void *device);
FooResult foo_gpu_discard(void *kernel);
FooResult foo_gpu_dispose(void *buffer);
FooResult foo_gpu_close(void *device);
FooResult foo_vulkan_available(void);
FooResult foo_vulkan_count(void);
FooResult foo_vulkan_open(void);
FooResult foo_vulkan_select(uint64_t index);
FooResult foo_vulkan_name(void *device);
FooResult foo_vulkan_reserve(void *device, uint64_t size);
FooResult foo_vulkan_upload(void *buffer, FooText source);
FooResult foo_vulkan_download(void *buffer, FooText destination);
FooResult foo_vulkan_compile(void *device, FooText code, uint64_t bindings,
                             uint64_t group);
FooResult foo_vulkan_bind(void *kernel, uint64_t index, void *buffer);
FooResult foo_vulkan_launch(void *kernel, uint64_t count);
FooResult foo_vulkan_dispatch(void *kernel, uint64_t count, uint64_t group);
FooResult foo_vulkan_plane(void *kernel, uint64_t x, uint64_t y,
                            uint64_t columns, uint64_t rows);
FooResult foo_vulkan_volume(void *kernel, uint64_t x, uint64_t y, uint64_t z,
                             uint64_t columns, uint64_t rows, uint64_t layers);
FooResult foo_vulkan_finish(void *device);
FooResult foo_vulkan_discard(void *kernel);
FooResult foo_vulkan_dispose(void *buffer);
FooResult foo_vulkan_close(void *device);
FooResult foo_text_release(FooText text);
FooResult foo_text_concatenate(FooText left, FooText right);
FooResult foo_text_trim(FooText text);
FooResult foo_text_length(FooText text);
FooResult foo_text_slice(FooText text, uint64_t first, uint64_t last);
FooResult foo_text_find(FooText text, FooText needle);
FooResult foo_io_input(void);
FooResult foo_io_output(void);
FooResult foo_io_report(void);
FooResult foo_io_read(void *stream, uint64_t size);
FooResult foo_io_line(void *stream);
FooResult foo_io_write(void *stream, FooText text);
FooResult foo_io_close(void *stream);
FooResult foo_fs_open(FooText path, FooText mode);
FooResult foo_fs_read(FooText path);
FooResult foo_fs_write(FooText path, FooText text);
FooResult foo_fs_load(FooText path);
FooResult foo_fs_save(FooText path, FooText bytes);
FooResult foo_fs_release(FooText bytes);
FooResult foo_fs_directory(FooText path);
FooResult foo_fs_scan(FooText path);
FooResult foo_fs_next(void *cursor);
FooResult foo_fs_finish(void *cursor);
FooResult foo_fs_join(FooText left, FooText right);
FooResult foo_fs_exists(FooText path);
FooResult foo_fs_kind(FooText path);
FooResult foo_fs_metadata(FooText path);
FooResult foo_fs_measure(void *metadata);
FooResult foo_fs_timestamp(void *metadata, FooText field);
FooResult foo_fs_classify(void *metadata);
FooResult foo_fs_restricted(void *metadata);
FooResult foo_fs_retire(void *metadata);
FooResult foo_fs_temporary(FooText directory, FooText prefix);
FooResult foo_fs_walk(FooText path);
FooResult foo_fs_traverse(void *cursor);
FooResult foo_fs_cease(void *cursor);
FooResult foo_fs_free(FooText path);
FooResult foo_fs_block(FooText path);
FooResult foo_fs_copy(FooText source, FooText destination);
FooResult foo_fs_working(void);
FooResult foo_fs_flush(void *stream);
FooResult foo_fs_sync(void *stream);
FooResult foo_fs_replace(FooText source, FooText destination);
FooResult foo_fs_remove(FooText path);
FooResult foo_fs_seek(void *stream, int64_t offset, FooText origin);
FooResult foo_fs_position(void *stream);
FooResult foo_fs_size(void *stream);
FooResult foo_fs_truncate(void *stream, uint64_t size);
FooResult foo_fs_reserve(void *stream, uint64_t size);
FooResult foo_fs_lock(void *stream, FooText mode);
FooResult foo_fs_unlock(void *stream);
FooResult foo_fs_readat(void *stream, uint64_t offset, FooText destination);
FooResult foo_fs_writeat(void *stream, uint64_t offset, FooText source);
FooResult foo_fs_fetch(void *stream, uint64_t offset, FooText destination);
FooResult foo_fs_store(void *stream, uint64_t offset, FooText source);
FooResult foo_fs_handle(void *stream);
FooResult foo_fs_map(FooText path, uint64_t offset, uint64_t length);
FooResult foo_fs_edit(FooText path, uint64_t offset, uint64_t length);
FooResult foo_fs_mapped(void *mapping);
FooResult foo_fs_borrow(void *mapping);
FooResult foo_fs_publish(void *mapping);
FooResult foo_fs_portion(void *mapping, uint64_t offset, uint64_t length);
FooResult foo_fs_unmap(void *mapping);
FooResult foo_vm_reserve(uint64_t size);
FooResult foo_vm_size(void *region);
FooResult foo_vm_commit(void *region);
FooResult foo_vm_protect(void *region, FooText mode);
FooResult foo_vm_decommit(void *region);
FooResult foo_vm_load(void *region, uint64_t offset);
FooResult foo_vm_store(void *region, uint64_t offset, uint8_t data);
FooResult foo_vm_release(void *region);
FooResult foo_fs_fault(FooText operation, uint64_t count);
FooResult foo_fs_clear(void);
FooResult foo_resource_files(void);
FooResult foo_resource_mapped(void);
FooResult foo_resource_threads(void);
FooResult foo_resource_tasks(void);
FooResult foo_resource_pending(void);
FooResult foo_metric_create(FooText name, FooText kind, FooText bounds);
FooResult foo_metric_add(void *meter, uint64_t amount);
FooResult foo_metric_set(void *meter, uint64_t amount);
FooResult foo_metric_observe(void *meter, uint64_t amount);
FooResult foo_metric_value(void *meter);
FooResult foo_metric_count(void *meter);
FooResult foo_metric_sum(void *meter);
FooResult foo_metric_bucket(void *meter, uint64_t index);
FooResult foo_metric_name(void *meter);
FooResult foo_metric_export(void *meter);
FooResult foo_metric_close(void *meter);
FooResult foo_trace_begin(FooText name);
FooResult foo_trace_current(void);
FooResult foo_trace_identity(void *span);
FooResult foo_trace_parent(void *span);
FooResult foo_trace_name(void *span);
FooResult foo_trace_finish(void *span);
FooResult foo_trace_elapsed(void *span);
FooResult foo_trace_close(void *span);
FooResult foo_limit_available(FooText kind);
FooResult foo_limit_soft(FooText kind);
FooResult foo_limit_hard(FooText kind);
FooResult foo_limit_set(FooText kind, uint64_t value);
FooResult foo_dylib_open(FooText path);
FooResult foo_dylib_lookup(void *library, FooText name);
FooResult foo_dylib_call(void *symbol, uint64_t argument);
FooResult foo_dylib_discard(void *symbol);
FooResult foo_dylib_close(void *library);
FooResult foo_ring_create(uint64_t capacity);
FooResult foo_ring_push(void *ring, uint8_t item);
FooResult foo_ring_prepend(void *ring, uint8_t item);
FooResult foo_ring_pop(void *ring);
FooResult foo_ring_remove(void *ring);
FooResult foo_ring_first(void *ring);
FooResult foo_ring_last(void *ring);
FooResult foo_ring_length(void *ring);
FooResult foo_ring_capacity(void *ring);
FooResult foo_ring_close(void *ring);
FooResult foo_bloom_create(uint64_t bits, uint64_t rounds);
FooResult foo_bloom_add(void *bloom, FooText key);
FooResult foo_bloom_contains(void *bloom, FooText key);
FooResult foo_bloom_bits(void *bloom);
FooResult foo_bloom_rounds(void *bloom);
FooResult foo_bloom_close(void *bloom);
FooResult foo_net_connect(FooText host, uint64_t port);
FooResult foo_net_listen(FooText host, uint64_t port);
FooResult foo_net_establish(uint64_t high, uint64_t low, uint64_t port, uint64_t scope);
FooResult foo_net_host(uint64_t high, uint64_t low, uint64_t port, uint64_t scope);
FooResult foo_net_accept(void *listener);
FooResult foo_net_port(void *listener);
FooResult foo_net_handle(void *socket);
FooResult foo_net_send(void *socket, FooText text);
FooResult foo_net_push(void *socket, FooText text);
FooResult foo_net_receive(void *socket, uint64_t size);
FooResult foo_net_shutdown(void *socket, FooText direction);
FooResult foo_net_latency(void *socket, bool enabled);
FooResult foo_net_probe(void *socket, bool enabled);
FooResult foo_net_timeout(void *socket, FooText direction, uint64_t milliseconds);
FooResult foo_net_supply(void *socket, FooText direction, uint64_t size);
FooResult foo_net_allocated(void *socket, FooText direction);
FooResult foo_net_expire(void *socket, uint64_t hops);
FooResult foo_net_classify(void *socket, uint64_t value);
FooResult foo_net_close(void *socket);
FooResult foo_tls_available(void);
FooResult foo_tls_connect(FooText host, uint64_t port);
FooResult foo_tls_send(void *connection, FooText content);
FooResult foo_tls_receive(void *connection, uint64_t size);
FooResult foo_tls_timeout(void *connection, FooText direction, uint64_t milliseconds);
FooResult foo_tls_close(void *connection);
FooResult foo_net_lookup(FooText host, FooText family);
FooResult foo_net_records(FooText host, FooText kind);
FooResult foo_net_amount(void *set);
FooResult foo_net_domain(void *set, uint64_t index);
FooResult foo_net_datum(void *set, uint64_t index);
FooResult foo_net_classification(void *set, uint64_t index);
FooResult foo_net_ttl(void *set, uint64_t index);
FooResult foo_net_forget(void *set);
FooResult foo_net_adapters(void);
FooResult foo_net_census(void *list);
FooResult foo_net_caption(void *list, uint64_t index);
FooResult foo_net_origin(void *list, uint64_t index);
FooResult foo_net_medium(void *list, uint64_t index);
FooResult foo_net_slot(void *list, uint64_t index);
FooResult foo_net_ceiling(void *list, uint64_t index);
FooResult foo_net_retire(void *list);
FooResult foo_net_routes(void);
FooResult foo_net_tally(void *list);
FooResult foo_net_target(void *list, uint64_t index);
FooResult foo_net_via(void *list, uint64_t index);
FooResult foo_net_protocol(void *list, uint64_t index);
FooResult foo_net_mask(void *list, uint64_t index);
FooResult foo_net_ordinal(void *list, uint64_t index);
FooResult foo_net_cost(void *list, uint64_t index);
FooResult foo_net_dismiss(void *list);
FooResult foo_net_parse4(FooText host);
FooResult foo_net_parse6high(FooText host);
FooResult foo_net_parse6low(FooText host);
FooResult foo_net_format4(uint32_t bits);
FooResult foo_net_format6(uint64_t high, uint64_t low);
FooResult foo_net_bind(FooText host, uint64_t port);
FooResult foo_net_local(void *socket);
FooResult foo_net_egress(void *socket, uint64_t index);
FooResult foo_net_affiliate(void *socket, FooText host, uint64_t port);
FooResult foo_net_affiliate6(void *socket, uint64_t high, uint64_t low, uint64_t port, uint64_t scope);
FooResult foo_net_submit(void *socket, FooText content);
FooResult foo_net_broadcast(void *socket, bool enabled);
FooResult foo_net_unicast(void *socket, uint64_t hops);
FooResult foo_net_traffic(void *socket, uint64_t value);
FooResult foo_net_buffer(void *socket, FooText direction, uint64_t size);
FooResult foo_net_capacity(void *socket, FooText direction);
FooResult foo_net_deadline(void *socket, FooText direction, uint64_t milliseconds);
FooResult foo_net_choose4(void *socket, uint32_t adapter);
FooResult foo_net_choose6(void *socket, uint64_t adapter);
FooResult foo_net_radius(void *socket, uint64_t hops);
FooResult foo_net_recirculate(void *socket, bool enabled);
FooResult foo_net_membership4(void *socket, uint32_t group, uint32_t adapter, bool enabled);
FooResult foo_net_membership6(void *socket, uint64_t high, uint64_t low, uint64_t adapter, bool enabled);
FooResult foo_net_transmit(void *socket, FooText host, uint64_t port, FooText content);
FooResult foo_net_transmit6(void *socket, uint64_t high, uint64_t low, uint64_t port, uint64_t scope, FooText content);
FooResult foo_net_collect(void *socket, uint64_t size);
FooResult foo_net_raw(void *packet);
FooResult foo_net_peer(void *packet);
FooResult foo_net_peer4(void *packet);
FooResult foo_net_peer6high(void *packet);
FooResult foo_net_peer6low(void *packet);
FooResult foo_net_zone(void *packet);
FooResult foo_net_source(void *packet);
FooResult foo_net_discard(void *packet);
FooResult foo_net_detach(void *socket);
FooResult foo_net_watch(void);
FooResult foo_net_stream(void *poller, void *socket, FooText direction, uint64_t token);
FooResult foo_net_packet(void *poller, void *socket, FooText direction, uint64_t token);
FooResult foo_net_process(void *poller, void *child, uint64_t token);
FooResult foo_net_alarm(void *poller, uint64_t token, uint64_t milliseconds);
FooResult foo_net_unwatch(void *poller, uint64_t token);
FooResult foo_net_ready(void *poller, uint64_t milliseconds);
FooResult foo_net_cease(void *poller);
FooResult foo_process_run(FooText command);
FooResult foo_process_execute(FooText program, FooText arguments);
FooResult foo_process_argument(uint64_t index);
FooResult foo_process_count(void);
FooResult foo_process_environment(FooText name);
FooResult foo_process_id(void);
FooResult foo_process_parent(void);
FooResult foo_process_spawn(FooText program, FooText arguments);
FooResult foo_process_pipe(FooText program, FooText arguments);
FooResult foo_process_write(void *child, FooText content);
FooResult foo_process_seal(void *child);
FooResult foo_process_read(void *child, FooText stream, uint64_t size);
FooResult foo_process_release(FooText content);
FooResult foo_process_identity(void *child);
FooResult foo_process_active(void *child);
FooResult foo_process_wait(void *child);
FooResult foo_process_observe(void *child, uint64_t milliseconds);
FooResult foo_process_kill(void *child);
FooResult foo_process_signal(void *child, FooText name);
FooResult foo_process_close(void *child);
FooResult foo_process_exit(uint8_t code);
FooResult foo_process_abort(void);
FooResult foo_time_current(void);
FooResult foo_time_wall(void);
FooResult foo_time_sleep(uint64_t nanos);
FooResult foo_timer_create(void);
FooResult foo_timer_arm(void *timer, uint64_t nanos);
FooResult foo_timer_wait(void *timer);
FooResult foo_timer_cancel(void *timer);
FooResult foo_timer_close(void *timer);
FooResult foo_thread_spawn(void (*function)(void *), void *context);
FooResult foo_thread_wait(void *thread);
FooResult foo_thread_mutex(void);
FooResult foo_thread_lock(void *mutex);
FooResult foo_thread_unlock(void *mutex);
FooResult foo_thread_condition(void);
FooResult foo_thread_signal(void *condition);
FooResult foo_thread_await(void *condition, void *mutex);
FooResult foo_thread_close(void *resource);
FooResult foo_task_backend(void);
FooResult foo_task_which(void);
FooResult foo_task_executor(void);
FooResult foo_task_block(void (*callback)(void));
FooResult foo_task_channel(void);
FooResult foo_task_send(void *channel, int64_t value);
FooResult foo_task_receive(void *channel, int64_t *output);
FooResult foo_task_scope(void);
FooResult foo_task_launch(void *scope, void (*callback)(int64_t), int64_t argument);
FooResult foo_task_cancel(void *scope);
FooResult foo_task_interrupt(void *pool);
FooResult foo_task_cancelled(void);
FooResult foo_task_join(void *scope);
FooResult foo_task_pool(void);
FooResult foo_task_submit(void *pool, void (*callback)(int64_t), int64_t argument);
FooResult foo_task_wait(void *pool);
FooResult foo_task_affinity(uint64_t cpu);
FooResult foo_task_label(FooText name);
#endif
